### PR TITLE
Test correction

### PR DESCRIPTION
**Pull request by pinzon**
Hi @kingster307 I made some small changes to your tests so they are successful with Localstack. 
Screenshot from 2022-07-25 10-14-51

```logs
>START RequestId: e0874d3b-3e96-19b0-e68a-a934033b6387 Version: $LATEST
> bucket - proj-bucket-prefix-20220725144527854900000001
> 
> key - presigned_url_prefix/cd57d1ae-735d-445b-81f1-0e5f95b38298
> 
> END RequestId: e0874d3b-3e96-19b0-e68a-a934033b6387
> REPORT RequestId: e0874d3b-3e96-19b0-e68a-a934033b6387        Init Duration: 151.49 ms        Duration: 2.25 ms       Billed Duration: 3 ms Memory Size: 1536 MB     Max Memory Used: 18 MB
2022-07-25T09:55:57.010 DEBUG --- [   asgi_gw_2] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-west-2:000000000000:function:s3CreatePresignedUrlLambda-3f10217 result / log output:
{"statusCode":200,"headers":{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"},"body":"{\"status\": true, \"message\": null, \"data\": {\"url\": \"https://proj-bucket-prefix-20220725144527854900000001.s3.amazonaws.com/\", \"fields\": {\"content-type\": \"csv\", \"x-amz-meta-action\": \"upload\", \"x-amz-meta-filename\": \"demo_file.csv\", \"key\": \"presigned_url_prefix/d9d8fe39-49ca-4a5e-9d18-a579fa75277c\", \"AWSAccessKeyId\": \"test\", \"policy\": \"eyJleHBpcmF0aW9uIjogIjIwMjItMDctMjVUMTU6NTU6NTZaIiwgImNvbmRpdGlvbnMiOiBbWyJlcSIsICIka2V5IiwgInByZXNpZ25lZF91cmxfcHJlZml4L2Q5ZDhmZTM5LTQ5Y2EtNGE1ZS05ZDE4LWE1NzlmYTc1Mjc3YyJdLCBbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwgMSwgMTAwMDAwMDAwMF0sIFsiZXEiLCAiJGNvbnRlbnQtdHlwZSIsICJjc3YiXSwgWyJlcSIsICIkeC1hbXotbWV0YS1hY3Rpb24iLCAidXBsb2FkIl0sIFsiZXEiLCAiJHgtYW16LW1ldGEtZmlsZW5hbWUiLCAiZGVtb19maWxlLmNzdiJdLCB7ImJ1Y2tldCI6ICJwcm9qLWJ1Y2tldC1wcmVmaXgtMjAyMjA3MjUxNDQ1Mjc4NTQ5MDAwMDAwMDEifSwgeyJrZXkiOiAicHJlc2lnbmVkX3VybF9wcmVmaXgvZDlkOGZlMzktNDljYS00YTVlLTlkMTgtYTU3OWZhNzUyNzdjIn1dfQ==\", \"signature\": \"hRCMhK31rY3iwB3+s52kG6OWR7g=\"}}}"}
>START RequestId: bb0d4de1-e3dd-172e-6db3-af706aaf9294 Version: $LATEST
> {'path': '/get_presigned_url', 'headers': {'Host': '5ug9edtdvf.execute-api.localhost.localstack.cloud:4566', 'User-Agent': 'python-requests/2.27.1', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'Connection': 'keep-alive', 'x-localstack-tgt-api': 'apigateway', 'X-Forwarded-For': '127.0.0.1, 5ug9edtdvf.execute-api.localhost.localstack.cloud:4566', 'x-localstack-edge': 'http://5ug9edtdvf.execute-api.localhost.localstack.cloud:4566', 'Authorization': ''}, 'multiValueHeaders': {'Host': ['5ug9edtdvf.execute-api.localhost.localstack.cloud:4566'], 'User-Agent': ['python-requests/2.27.1'], 'accept-encoding': ['gzip, deflate'], 'accept': ['*/*'], 'Connection': ['keep-alive'], 'x-localstack-tgt-api': ['apigateway'], 'X-Forwarded-For': ['127.0.0.1, 5ug9edtdvf.execute-api.localhost.localstack.cloud:4566'], 'x-localstack-edge': ['http://5ug9edtdvf.execute-api.localhost.localstack.cloud:4566'], 'Authorization': ['']}, 'body': '', 'isBase64Encoded': False, 'httpMethod': 'GET', 'queryStringParameters': {'action': 'upload', 'file_name': 'demo_file.csv', 'content_type': 'csv'}, 'multiValueQueryStringParameters': {'action': ['upload'], 'file_name': ['demo_file.csv'], 'content_type': ['csv']}, 'pathParameters': {}, 'resource': '/get_presigned_url', 'requestContext': {'accountId': '000000000000', 'apiId': '5ug9edtdvf', 'resourcePath': '/get_presigned_url', 'domainPrefix': '5ug9edtdvf', 'domainName': '5ug9edtdvf.execute-api.localhost.localstack.cloud', 'resourceId': 'dv7378074i', 'requestId': '320d7ed0-3091-415c-8d05-a70359b0b8bf', 'identity': {'accountId': '000000000000', 'sourceIp': '127.0.0.1', 'userAgent': 'python-requests/2.27.1'}, 'httpMethod': 'GET', 'protocol': 'HTTP/1.1', 'requestTime': '25/Jul/2022:14:55:56 +0000', 'requestTimeEpoch': 1658760956206, 'authorizer': {'context': {}, 'identity': {}}, 'path': '/api/get_presigned_url', 'stage': 'api'}, 'stageVariables': {}}
> END RequestId: b...
2022-07-25T09:55:57.124  INFO --- [   asgi_gw_2] localstack.request.http    : GET /api/get_presigned_url => 200
2022-07-25T09:55:57.225 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda executed in Event (asynchronous) mode, no response will be returned to caller
2022-07-25T09:55:57.228  INFO --- [  Thread-272] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-8491fcc
2022-07-25T09:55:57.229 DEBUG --- [  Thread-272] l.u.c.docker_cmd_client    : Create container with cmd: ['docker', 'create', '--rm', '-v', '/home/cristopher/Projects/localstack/.filesystem/var/lib/localstack/tmp/zipfile.81a0f4b9:/var/task', '--interactive', '-e', 'AWS_ACCESS_KEY_ID=test', '-e', 'AWS_SECRET_ACCESS_KEY=test', '-e', 'AWS_REGION=us-west-2', '-e', 'DOCKER_LAMBDA_USE_STDIN=1', '-e', 'LOCALSTACK_HOSTNAME=172.17.0.1', '-e', 'EDGE_PORT=4566', '-e', '_HANDLER=lambda_function.lambda_handler', '-e', 'AWS_LAMBDA_FUNCTION_TIMEOUT=900', '-e', 'AWS_LAMBDA_FUNCTION_NAME=s3OnObjectCreatedLambda-8491fcc', '-e', 'AWS_LAMBDA_FUNCTION_VERSION=$LATEST', '-e', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-8491fcc', '--network', 'bridge', 'lambci/lambda:python3.7', 'lambda_function.lambda_handler']
2022-07-25T09:55:57.230 DEBUG --- [  Thread-272] localstack.utils.run       : Executing command: ['docker', 'create', '--rm', '-v', '/home/cristopher/Projects/localstack/.filesystem/var/lib/localstack/tmp/zipfile.81a0f4b9:/var/task', '--interactive', '-e', 'AWS_ACCESS_KEY_ID=test', '-e', 'AWS_SECRET_ACCESS_KEY=test', '-e', 'AWS_REGION=us-west-2', '-e', 'DOCKER_LAMBDA_USE_STDIN=1', '-e', 'LOCALSTACK_HOSTNAME=172.17.0.1', '-e', 'EDGE_PORT=4566', '-e', '_HANDLER=lambda_function.lambda_handler', '-e', 'AWS_LAMBDA_FUNCTION_TIMEOUT=900', '-e', 'AWS_LAMBDA_FUNCTION_NAME=s3OnObjectCreatedLambda-8491fcc', '-e', 'AWS_LAMBDA_FUNCTION_VERSION=$LATEST', '-e', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-8491fcc', '--network', 'bridge', 'lambci/lambda:python3.7', 'lambda_function.lambda_handler']
2022-07-25T09:55:57.238  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.DeleteObjects => 204
2022-07-25T09:55:57.299 DEBUG --- [  Thread-272] l.u.c.docker_cmd_client    : Start container with cmd: ['docker', 'start', '--interactive', '--attach', 'ce18222e4f5ff0b6b95c5ca84e1e04f89f977017bbb00660c1a564d56604db42']
2022-07-25T09:55:57.299 DEBUG --- [  Thread-272] localstack.utils.run       : Executing command: ['docker', 'start', '--interactive', '--attach', 'ce18222e4f5ff0b6b95c5ca84e1e04f89f977017bbb00660c1a564d56604db42']
2022-07-25T09:55:57.890 DEBUG --- [  Thread-272] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-8491fcc result / log output:
null
>START RequestId: 0d649a4a-95d9-1095-d79d-41b25e05e5f1 Version: $LATEST
> bucket - proj-bucket-prefix-20220725144527854900000001
> 
> key - presigned_url_prefix/d9d8fe39-49ca-4a5e-9d18-a579fa75277c
```

### CODE REVIEW

**Comment by peterkingswe** [comment]
changes do not work....not sure what localstack config you're using... by removing `up` from makefile `all` recipe I assume you have an external instance that you're running against....added back in up recipe locally so that everything would build & these are the resulting logs...added `up` back in [here](https://github.com/pinzon/localstack_onObjectCreated_bug/blob/fix-tests/Makefile)

Screen Shot 2022-07-25 at 12 27 08 PM

**Comment by pinzon** [comment]
my bad about the `up` command, could you try to set your endpoints to `localhost.localstack.cloud:4566`, and set the env variable `LOCALSTACK_HOSTNAME` to` localhost.localstack.cloud`?

**Comment by peterkingswe** [comment]
still no luck...no longer get 404 but logs still don't show up for some reason...see todo's in test but tried prepending bucket to new url & tried like you have it in your logs above but still not able to get it to work
Screen Shot 2022-07-25 at 1 13 04 PM

**Comment by pinzon** [comment]
**@kingster307 that first log from LocalStack shows that your function is being found and executed** but you should not rely on the docker logs of the lambda container due to being unreliable in some setups or consoles, you should make your lambda function return something or do something. 

In my last commit I added that the triggered lambda returns an array, but in other cases some users make their lambda send a request to their [temporal webhook site](https://webhook.site/) or in localstack/localstack/pull/6498 I validate that the lambda is being executed because it writes into a dynamo DB
Screenshot from 2022-07-25 12-31-41

**Comment by peterkingswe** [comment]
@pinzon The return in the lambda seems to have no effect...if s3 is triggering lambda then it doesn't seem the lambda return would make it back to client caller

even when utilizing aws cli logs nothing shows `aws --profile localstack --endpoint-url=http://localhost:4566 logs tail /aws/lambda/s3OnObjectCreatedLambda-032ce5e --follow` --> makefile `make get-logs-s3-on-object-created`

Screen Shot 2022-07-25 at 2 30 22 PM


Will try new url structure in our project test to see if that works

**Comment by pinzon** [comment]
@kingster307 yes you're right I tested your issue with a docker container and the logs are not showing, It has to do with docker-compose, but if you run the container directly, it shows the logs. You can avoid writing the docker command if you **install the localstack command**. `pip install localstack` more details in the README file.

Since we agreed that your Lambda function is being triggered by the presign POST, I'm going close the issue.

**Pull request merged**
